### ISSUE TITLE
Replace for-loops in phylocurve.R

### ISSUE THREAD

**Issue by nlhuong** [davidnipperess/PDcalc#1]
I found that the double for loop in the phylocurve function seems to be rather computationally prohibitive.
I suggest you vectorize instead and replace lines (142-146, 157-161) with the following which gives a substantial speed up:

varmat <- varmat - t(1 - p) %*% (1 - p)

**Comment by davidnipperess** [comment]
Thanks very much for pointing that out. I will implement in the next version.

Thanks again.

**Comment by davidnipperess** [comment]
Phylocurve is now updated with vectorised code. Not quite as simple as suggested (because of accumulation by sites option) but solution found. Function should perform considerably faster now.
