### ISSUE TITLE
Consultation: Considering weights of species in PD score

### ISSUE THREAD

**Issue by halabikeren** [davidnipperess/PDcalc#2]
Hello,

I was wondering if maybe you could help me with an issue I've encountered while attempting to consider species weights in "weighted PD" calculations.

I have a phylogenetic tree and a weights function that maps a weight to each taxon in the tree.

I would like to create a combination of the PD scores and the weights of the chosen taxa.

I tried using the linear combination a*PD(S) +weights(S) suggested [here](https://academic.oup.com/sysbio/article-lookup/doi/10.1080/10635150590947023). Unfortunately, while I can use the "a" parameter to somewhat control the significance of each element in the suggested formula, I cannot use this formulation to "standardize" the difference of the orders of magnitude of both functions: the PD and the weights function). For example, if the summations of weights of different subsets of taxa are closer to one another than their PD scores, the PD element would still end up having a higher significance in the choice of the subset than the weights.

I would like to overcome this difference in the orders of magnitude of both functions.

Do you have any suggestion regarding standardization of the orders of magnitude of the weights function?

Thanks in advance!

**Comment by davidnipperess** [comment]
Hi

Firstly, this is a place for posting issues with the software, not for posting particular mathematical problems you are trying to solve. However, I will give my opinion on your problem.

If I am understanding correctly (which I may not), then the issue with balancing between PD and species weights just comes down to the range of values assigned to branch lengths versus species weights. For branch lengths, I would be inclined to rescale them relative to the depth of the tree (assuming a rooted tree). So, if the age of the oldest node is 60, then divide all branch lengths by this value. This has the advantage of making PD be interpretable as the "number of independent lineages" as the sum of branch lengths connecting any one species to the root will be 1. See [here](http://rstb.royalsocietypublishing.org/content/365/1558/3599) for more on this. By the same logic, each species weight should range from -1 to 1.
